### ISSUE TITLE
Revert 1.12.X

### ISSUE THREAD

**Issue by SnowfallWoW** [SnowfallWoW/Issues#2]
This issue servers as a to-do to revert build 1.12.1 to 1.11.1.

**Patches**
- [x] 1.12 
- [x] 1.12.1
- [x] 1.12.2

This patch had no removed content

**Comment by Argonn** [comment]
Class changes
-[ ] Druids
-[ ] Hunters
-[ ] Mages
-[ ] Paladin
-[ ] Priest
-[ ] Rogue
-[ ] Shaman
-[ ] Warlock
-[ ] Warrior

-[ ] Item changes
-[ ] Profession changes

Raid and dungeons
-[ ] Uldaman
-[ ] Zul'Farrak
-[ ] Maraudon
-[ ] Ahn'Qiraj

-[ ]  World environment changes

**Comment by Argonn** [comment]
There are still some issues with creature stats/spells, which I'm not happy about.

**Comment by SnowfallWoW** [comment]
Issue moved to [SnowfallWoW/Patch-reversion #2](https://github.com/SnowfallWoW/Patch-reversion/issues/2) via [**ZenHub.io**](https://www.zenhub.io/)
