### ISSUE TITLE
Revert 1.11.X

### ISSUE THREAD

**Issue by Argonn** [SnowfallWoW/Issues#7]
This issue servers as a to-do to revert build 1.11.X
- [ ] General
- [ ] Alterac Valley
- [ ] Class changes
- [ ] Items
- [ ] Professions
- [ ] Quests
- [ ] Raids and Dungeons
- [ ] World Enviroment
- [x] Removed Content

**Comment by Argonn** [comment]
All patch changes that we can modify have been listed here:
https://snowfallwow.com/forum/viewtopic.php?f=29&t=30&p=50#p50

**Comment by SnowfallWoW** [comment]
Issue moved to [SnowfallWoW/Patch-reversion #1](https://github.com/SnowfallWoW/Patch-reversion/issues/1) via [**ZenHub.io**](https://www.zenhub.io/)
